## Упражнения по библиотеке Numpy

In [2]:
import numpy as np
import random

def random_matrix(dim1 = 1, dim2 = 1, alen = 10, imin = 1, imax = 4):
    new_matrix = np.array([random.randrange(imin, imax) for _ in range(alen)])
    
    if (dim1 != 1 or dim2 != 1):
        return new_matrix.reshape(dim1, dim2)
    else:
        return new_matrix

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
np.random.shuffle(random_array:=np.arange(4))
random_array[(random_array >= 3) & (random_array <= 8)] *= -1;
print(random_array)


[ 0  1 -3  2]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
random_array[random_array.argmax()] = 0
print(random_array)

[ 0  1 -3  0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
print(np.stack(np.meshgrid(*(matrix := random_array.reshape(-1, 2)), indexing='ij'), axis=-1).reshape(-1, matrix.shape[0]))

[[ 0 -3]
 [ 0  0]
 [ 1 -3]
 [ 1  0]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
np.random.shuffle(A:= np.arange(24).reshape(8, 3))
np.random.shuffle(B:= np.arange(4).reshape(2,2))
print(A[np.isin(A, B[0]).any(axis=1) & np.isin(A, B[1]).any(axis=1)])


[[0 1 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
big_matrix = random_matrix(10, 3, 30, 1, 5)
print(big_matrix[(big_matrix != big_matrix[:, [0]]).any(axis = 1)])

[[4 2 3]
 [4 1 3]
 [4 3 3]
 [4 1 3]
 [4 4 1]
 [2 3 4]
 [2 2 1]
 [4 1 3]
 [4 3 2]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
two_dim_array = random_matrix(-1, 2, 10, imin=1, imax=3)
print(np.unique(two_dim_array, axis=0))

[[1 1]
 [1 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
rect_matrix = random_matrix(10, -1, 100, 0, 3)
print(rect_matrix)

# 1 - no numpy
X = 1
for i in range(rect_matrix.shape[1]):
    X *= rect_matrix[i][i] != 0 and rect_matrix[i][i] or 1
print(X)

# 2 - numpy
print(np.prod(np.diag(rect_matrix)[np.diag(rect_matrix) != 0]))

[[1 1 0 1 2 0 1 0 2 0]
 [1 0 0 2 1 2 2 1 0 1]
 [1 2 1 1 0 2 2 0 2 2]
 [2 1 2 2 0 0 2 0 2 2]
 [0 2 1 2 1 0 0 0 1 2]
 [0 1 0 0 0 1 1 1 2 1]
 [0 1 1 2 2 0 0 2 0 0]
 [1 1 2 1 2 2 0 1 1 2]
 [0 0 2 2 2 0 1 1 1 2]
 [2 0 1 0 2 1 1 1 1 1]]
2
2


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
x, y = np.array([random_matrix(1, 1, 10, 0, 2), random_matrix(1, 1, 10, 0, 2)])
x2 = x.copy()
y2 = y.copy()
print(x)
print(y)

# 1 - no numpy
def partition(ArrayLike: object, left: int, right: int):
    pivot = ArrayLike[right]
    i = left - 1
    for j in range(left, right):
        if (ArrayLike[j] < pivot):
            i += 1
            ArrayLike[j], ArrayLike[i] = ArrayLike[i], ArrayLike[j]
    pr = i + 1
    ArrayLike[pr], ArrayLike[right] = ArrayLike[right], ArrayLike[pr]
    return pr
            

def quick_sort(ArrayLike: object, left: int, right: int):
    if (left >= right): return
    pr = partition(ArrayLike, left, right)
    quick_sort(ArrayLike, left, pr - 1)
    quick_sort(ArrayLike, pr + 1, right)


quick_sort(x, 0, len(x)-1)
quick_sort(y, 0, len(y)-1)
print((x == y).all())

# 2 - numpy
print((np.sort(x2) == np.sort(y2)).all())

[1 1 1 0 1 0 1 0 1 0]
[1 0 1 1 1 1 0 1 1 1]
False
False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [11]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

# 1 - no numpy
print(max((x[i] for i in range(1, len(x)) if x[i-1] == 0), default=-1))

# 2 - numpy
print(np.max(x[1:][x[:-1] == 0]))


5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
x = np.array([2, 2, 2, 3, 3, 3, 5])

# 1 - no numpy
counts = {}
for v in x:
    counts[int(v)] = counts.get(int(v), 0)  + 1
print((np.array([k for k in counts.keys()]), np.array([v for v in counts.values()])))

# 2 - numpy
changes = np.r_[True, x[:-1] != x[1:], True]
result = (x[changes[:-1]], np.diff(np.where(changes)[0]))
print(result)

(array([2, 3, 5]), array([3, 3, 1]))
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [13]:
from time import time
from scipy.spatial.distance import cdist

X = np.random.rand(100, 50)
Y = np.random.rand(150, 50)

tick = time()
distance_matrix = np.asarray([[np.sqrt(np.sum((X[i] - Y[j])**2)) for j in range(Y.shape[0])] for i in range(X.shape[0])])
print(f"{time() - tick}s")

tick = time()
cdist(X, Y, 'euclidean')
print(f"{time() - tick}s")



0.07874345779418945s
0.000858306884765625s


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [15]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [16]:
avarage_calories = np.average(calorie_stats)
print(f"В среднем {avarage_calories} калорий")

В среднем 106.88311688311688 калорий


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [17]:
calorie_stats_sorted = np.sort(calorie_stats, )
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [18]:
median_calories = np.median(calorie_stats)
print(f"Медиана: {median_calories}")

Медиана: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [19]:
nth_percentile = 0
for i in range(1, 101):
    percentile = np.percentile(calorie_stats, i)
    print(f"Процентиль [{i}]: {percentile}")
    if (percentile > 60):
        nth_percentile = percentile
        break

Процентиль [1]: 50.0
Процентиль [2]: 50.0
Процентиль [3]: 55.599999999999994
Процентиль [4]: 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [20]:
more_calories = np.percentile(calorie_stats, 60)
print(f"Процент хлопьев, в которых содержится более 60 калорий на порцию: {(1 - np.sum([v for v in calorie_stats if v < 60])/np.sum(calorie_stats))*100}%")

Процент хлопьев, в которых содержится более 60 калорий на порцию: 98.17739975698665%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [21]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
"""
Анализ показывает, что среднее количество калорий в хлопьях конкурентов составляет примерно 107 калорий, 
при этом большинство продуктов (около 68%) находятся в диапазоне от 87 до 127 калорий. 
Это позволяет позиционировать CrunchieMunchies стратегически: 
если их калорийность ниже 87, можно смело рекламировать их как "значительно более лёгкий и здоровый выбор".
"""